### ISSUE TITLE
Convert to PDF does not render images

### ISSUE THREAD

**Issue by MrKalach** [asciidoctor/asciidoctor-vscode#568] opened 2022-05-04 07:37 UTC
## Description

Convert to PDF doesn't render images. Images can be rendered by using a workaround: use absolute path in `:imagesdir:`
At the same time, in preview images are present.

## System Information

- OS: Windows 10
- VSCode 1.66.2
- AsciiDoc v2.9.8
- Default plugin settings

## To Reproduce

Steps to reproduce the issue:

1. Download [test_adoc.zip](https://github.com/asciidoctor/asciidoctor-vscode/files/8618602/test_adoc.zip) and unpack it
2. Open `test_adoc` folder in VSCode
3. Goto to `some_manual` folder and open `index.adoc`
4. `Export document as PDF`
5. open `index.pdf` and see no images

## Screenshots & Files

Preview:
![image](https://user-images.githubusercontent.com/3017441/166639515-edc54185-3c20-4334-8100-da988cb13450.png)

PDF:
![image](https://user-images.githubusercontent.com/3017441/166639578-626ab56a-b57e-4ccd-9395-168bb2f44b15.png)

Exported PDF: [index.pdf](https://github.com/asciidoctor/asciidoctor-vscode/files/8618563/index.pdf)

**Comment by Mogztter** [comment] 2022-06-21 19:55
Probably a duplicate of https://github.com/asciidoctor/asciidoctor-vscode/issues/487

**Closed** 2022-06-26 14:07 UTC
Labels: 🐞 bug, duplicate
