### ISSUE TITLE
Issue with Table and Merged cells

### ISSUE THREAD

**Issue by renzhentaxi** [asciidoctor/asciidoctor-vscode#159] opened 2019-01-17 18:06 UTC
The preview seems to be bugged when you apply cols format on a table with merged cells.

```
[cols="s,1"]
|===
|header |header

.2+|merged cell
|should not be bold
|should not be bold
|===
```

I expected the preview to something like this:
![expected](https://user-images.githubusercontent.com/6445762/51338736-43e07480-1a50-11e9-9712-2a13632aa90d.PNG)

but it actually came out like this:

![actual](https://user-images.githubusercontent.com/6445762/51338754-4f33a000-1a50-11e9-9d76-da46a87784bd.PNG)

**Comment by MatteoCampinoti94** [comment] 2019-01-17 20:58
I'm not sure why Asciidoctor renders it that way. Every version of Asciidoctor I've tried with that table renders it with the second merged cell in bold when using `cols="s,1"`. Omitting that attribute renders the table as you'd expect, so the culprit is most likely the value you used.

Furthermore, this is a rendering issue, which is caused by either asciidoctor or asciidoctor.js depending on your settings, neither of which are maintained in this repo. This extension only uses them, it simply feeds the document content to the executable and shows you the result.

Try taking a look at the tables section of the full user manual [asciidoctor.org/docs/user-manual/#tables](https://asciidoctor.org/docs/user-manual/#tables), the solution might be there. I'll take a look at the manual too and add a comment here if I find anything relevant.

If we can't solve it, open the issue on [asciidoctor/asciidoctor](/asciidoctor/asciidoctor), they know more about the ins and outs of asciidoctor there.

**Closed by MatteoCampinoti94** 2019-01-17 20:58 UTC

**Comment by renzhentaxi** [comment] 2019-01-17 21:23
I see. it appears to be a known issue since 2015 :(
https://github.com/asciidoctor/asciidoctor/issues/1558

**Comment by MatteoCampinoti94** [comment] 2019-01-18 09:43
Apparently yes :(

Omitting the cols attribute visualizes it properly so at least there is that.
