### ISSUE TITLE
Extension host crashes when using together with "zignd.html-css-class-completion"

### ISSUE THREAD

**Issue by IlCallo** [asciidoctor/asciidoctor-vscode#162] opened 2019-02-08 12:04 UTC
After last VSCode update, the entire extension mechanism crashes if I'm using together this extension and "zignd.html-css-class-completion".

I get the following errors but I don't know if they're actually related.

> ERR tokens.filter is not a function: TypeError: tokens.filter is not a function
    at MarkdownFoldingProvider.<anonymous> (C:\Users\Paolo\.vscode\extensions\joaompinto.asciidoctor-vscode-2.3.3\src\features\foldingProvider.ts:28:32)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Paolo\.vscode\extensions\joaompinto.asciidoctor-vscode-2.3.3\out\src\features\foldingProvider.js:8:58)

> Extension host terminated unexpectedly. Code:  3221225725  Signal:  null
t._onExtensionHostCrashed @ extensionService.ts:457

I can also see that "zignd.html-css-class-completion" takes almost no time to initialize when this extension is disabled, while taking more than a minute when they are both enabled.

Everything works fine if I disable one or the other.

____
System information:

Versione: 1.31.0 (user setup)
Commit: 7c66f58312b48ed8ca4e387ebd9ffe9605332caa
Data: 2019-02-05T22:35:56.624Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

**Comment by MatteoCampinoti94** [comment] 2019-02-08 12:14
The `MarkdownFoldingProvider` error is already known, it will be fixed when we start overhauling the extension. Atm it does not cause anything more than that error.

I dont know that other extension you are using, what does it do exactly?

Also, what do you mean exactly with 'user setup' in the version number?

**Comment by IlCallo** [comment] 2019-02-08 16:02
> I dont know that other extension you are using, what does it do exactly?
[https://marketplace.visualstudio.com/items?itemName=Zignd.html-css-class-completion](Here the marketplace page)

> Also, what do you mean exactly with 'user setup' in the version number?
Don't really know, I just copied all info from from VSCode "About" section under "Help".
I guess it's about being installed only for my user and not system-wide.

**Comment by MatteoCampinoti94** [comment] 2019-02-08 16:06
I'll check it out.

Okay. I do not have a windows machine to try things on, but will check if the bug occurs on Linux as well.

**Comment by MatteoCampinoti94** [comment] 2019-02-08 16:14
I have no problems at all on Linux, works like a charm like usual.

Could you try two things?
* 1
Open VSCode in a new folder.
You should be able to from powershell/cmd: `path/to/vscode.exe .`
* 2
Open VSCode with default settings.
Simply temporarily remove your `settings.json` file.

**Comment by IlCallo** [comment] 2019-02-08 17:18
> Open VSCode in a new folder.
Tryed it (two times to be sure), using command `C:\Users\Paolo\AppData\Local\Programs\"Microsoft VS Code"\Code.exe`
**zignd.html-css-class-completion** is still slow like hell, but apparently nothing crashes.
Also, CPU usage is 35%, seems too high to me for normal behaviour.

> Simply temporarily remove your `settings.json` file.
You mean the one of my workspace? Or is there a general one per-installation? I don't really know where to find that, I'm using the one of the workspace.

Would you like the list of all extensions I installed? Could be useful?

**Comment by MatteoCampinoti94** [comment] 2019-02-09 19:44
That's very so weird.

Settings file for Windows is located at `%APPDATA%\Code\User\settings.json`, you can just temporarily move it to the desktop.

A list of your extensions would be useful yes, thanks.

**Comment by IlCallo** [comment] 2019-02-11 08:15
Here's the list.

* Angular 7 Snippets / `mikael.angular-beastcode`;
* Angular Console / `nrwl.angular-console`;
* Angular Language Service / `angular.ng-template`;
* AsciiDoc / `joaompinto.asciidoctor-vscode`;
* GitLens / `eamodio.gitlens`;
* HTML CSS support / `ecmel.vscode-html-css`;
* IntelliSense for CSS class names in HTML / `zignd.html-css-class-completion`;
* Italian Language Pack for Visual Studio Code / `ms-ceintl.vscode-language-pack-it`;
* Jest / `orta.vscode-jest`;
* Prettier / `esbenp.prettier-vscode`;
* TSLint / `eg2.tslint`;
* Typescript Hero / `rbbit.typescript-hero`;
* Document this / `joelday.docthis`;
* gitflow / `vector-of-bool.gitflow`.

**Comment by MatteoCampinoti94** [comment] 2019-02-11 11:25
Can you disable all extensions except for `joaompinto.asciidoctor-vscode` and `zignd.html-css-class-completion`? See if the crash occurs when those are the only extensions.
I'll try installing the same extensions you have, see if anything happens.

**Comment by MatteoCampinoti94** [comment] 2019-02-11 11:38
Installed them and have no error whatsover (exceot for the `tokens.filter`, but that's internal to our extensions only)

**Comment by MatteoCampinoti94** [comment] 2019-02-11 11:46
It may be some weird combination of extensions and settings, you should try making a completely clean install.
Remove `%APPDATA%\Code` and `%USERPROFILE%\.vscode`, the first folder contains settings, opened folders, etc...  the second contains the extensions (remember to backup your `settings.json` first).
With that done, try uninstalling VSCode itself and reinstalling it and all your extensions.

**Comment by IlCallo** [comment] 2019-02-13 10:18
Did a fresh install, added previous settings and keybindings and it worked.
Added the two packages and it worked.
Added all previous extensions and I noticed that TSLint plugin changed (there is now an official one supported my Microsoft).
When I installed that (but I think it was the same with the previous one), everything started to go slow.

I disabled all other extensions except those 3 (yours, TSLint and the incriminated one) and it started working fast again 🙃 

I re-enabled all extensions and now **zignd.html-css-class-completion** is again super-slow but not crashy.
At this point my assumption is that too many "heavy" (?) extensions loaded together are not a good idea and probably it's not directly related to this extension.

You can close the issue, if you think it's not worth the time to explore it deeper.

**Comment by MatteoCampinoti94** [comment] 2019-02-13 10:20
It's more likely that they interact with each other, extensions are loaded on demand in vscode, so one (or more) of them might be doing something weird.

Could you look at the dev console and see if there us any error trace when it slows down?

**Comment by MatteoCampinoti94** [comment] 2019-02-13 10:21
You can toggle it in the command pallette: `toggle developer tools`

**Comment by IlCallo** [comment] 2019-02-13 10:28
![image](https://user-images.githubusercontent.com/10036108/52705064-4caa6480-2f82-11e9-8b87-3c7f13dc8ab9.png)

This, and it keeps repeating the last two "extension host" message every now and then

**Comment by MatteoCampinoti94** [comment] 2019-02-13 10:37
Hmmm, I'm not 100% sure butt I think one of the extensions dealing with CSS is trying to open all documents

**Comment by MatteoCampinoti94** [comment] 2019-02-13 10:37
Not sure what the last two are for, but I guess it's a debugger for js you started, or the linter

**Comment by IlCallo** [comment] 2019-02-28 19:29
Anyway I just removed the extension, given that I couldn't find the culprit. Should I close the issue?

**Comment by MatteoCampinoti94** [comment] 2019-02-28 19:31
Not yet, we'll keep it open for further future investigation. Maybe we will find something that caused it.

**Comment by danyill** [comment] 2020-05-12 20:00
I think we'll close this for now -- the error in the screenshot about the folding provider (`tokens.filter`) has been removed (by disabling it for now) and 14 months is a long time in VS Code time. 

It seems possible this was caused by the third party extension. I installed the latest version (1.19.0) of this extension and found no poor interactions with the Asciidoc document.

Feel free to reopen if this is still an issue for you.

**Closed by danyill** 2020-05-12 20:00 UTC
Labels: bug, windows

**Comment by IlCallo** [comment] 2020-05-12 20:12
I didn't use it again since last year, but right now TSLint is deprecated and everything moved to ESLint, the issue is probably not relevant anymore
