### ISSUE TITLE
VSCode Web doesn't open asciidoc preview

### ISSUE THREAD

**Issue by gfinger** [asciidoctor/asciidoctor-vscode#781] opened 2023-08-17 14:47 UTC
I open an Asciidoc file in VSCode Web in a repository on GitHub. The asciidoc extension is installed, the editor works fine, but the preview doesn't open. The error message is "command 'asciidoc.showPreviewToSide' not found". Is the preview supposed to work in VSCode Web?

**Comment by ggrossetie** [comment] 2023-08-17 15:12
This is a duplicate of: https://github.com/asciidoctor/asciidoctor-vscode/issues/770
It's already fixed on the master branch and will be released soon.

**Closed by ggrossetie** 2023-08-17 15:12 UTC
Labels: 🐞 bug
