### ISSUE TITLE
Command 'AsciiDoc: Open Preview' resulted in an error

### ISSUE THREAD

**Issue by labolado** [asciidoctor/asciidoctor-vscode#826] opened 2023-11-23 02:38 UTC
AsciiDoc v3.1.9

error msg:
Command 'AsciiDoc: Open Preview' resulted in an error
command 'asciidoc.showPreview' not found

screenshot:
<img width="249" alt="image" src="https://github.com/asciidoctor/asciidoctor-vscode/assets/12539642/9b26d40b-d851-4b1b-aba7-385eb9373a26">

visual studio code:
Version: 1.84.2 (Universal)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:52:33.687Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.6.0

macOS 13.5 (m2)

**Comment by ggrossetie** [comment] 2023-11-24 09:29
@labolado Could you please try to remove all other extensions and reinstall the Asciidoctor VS Code extension?
This error most likely happens when the extension is not properly installed or when there's a conflict with another extension.

**Comment by rimuln** [comment] 2023-12-26 11:55
In my case it was conflict with Better AsciiDoc (Orielly style) v0,0,7

**Comment by ggrossetie** [comment] 2023-12-27 16:13
I'm pretty sure the error message is caused by a plugin conflict. I'm closing this issue, feel free to join https://chat.asciidoctor.org/ if you need help.

**Closed by ggrossetie** 2023-12-27 16:13 UTC
Labels: 🐞 bug
