### ISSUE TITLE
This `*` and `*` that breaks syntax highlighting

### ISSUE THREAD

**Issue by peterquiel** [asciidoctor/asciidoctor-vscode#197] opened 2019-05-10 08:26 UTC
The following code snippet breaks syntax highlighting;

```
This `*` and `*` that breaks syntax highlighting
```

![image](https://user-images.githubusercontent.com/13017110/57513253-1759ac80-730e-11e9-84a1-c714667b9261.png)

**Comment by MatteoCampinoti94** [comment] 2019-05-12 13:50
Damn, I hoped I had fixed all of these match errors x.x

The problem is caused by the matches including each other, it's necessary to properly highlight things like __*bold italic*__,  Unfortunately there are some edge cases where it wreaks havoc, as you noticed.

I should be able to fix this, but I do not have an ETA, need to study it carefully or it might cause more problems down the line.

**Comment by danyill** [comment] 2020-02-14 01:27
This doesn't break syntax highlighting any more:

![image](https://user-images.githubusercontent.com/674783/74493082-e1e58d80-4f35-11ea-9119-839a1e1c07f0.png)

We also don't highlight back-ticks with the new syntax language (unfortunately) but the syntax shown it doesn't adversely affect the rest of the document.

So I'll close this -- feel free to reopen if I've misunderstood.

**Closed by danyill** 2020-02-14 01:27 UTC
Labels: bug
