### ISSUE TITLE
Cursor keys stop working

### ISSUE THREAD

**Issue by igarashitm** [asciidoctor/asciidoctor-vscode#166] opened 2019-02-20 21:23 UTC
I installed asciidoctor-vscode 2.3.3 in VSCode 1.31.1 and then cursor key stopped working. On Fedora 29. I found that even in other editor than .adoc, it needs 5 seconds to move the cursor after press the cursor key. It got back working like before after I uninstall asciidoctor-vscode.

**Comment by MatteoCampinoti94** [comment] 2019-02-22 00:32
You should post your VSCode about output too, and the list of installed extensions so we can see if the problem is indeed caused by our extension.

I do not have a Fedora machine, so you might have to try out some changes yourself if it is indeed our extension's fault.

**Comment by MatteoCampinoti94** [comment] 2019-03-15 12:37
Closing down the issue since @igarashitm hasn't shared any details and the issue doesn't happen on my machines.

**Closed by MatteoCampinoti94** 2019-03-15 12:37 UTC
