### ISSUE TITLE
Image not shown by preview when there is a space in path

### ISSUE THREAD

**Issue by ulrichsch** [asciidoctor/asciidoctor-vscode#347] opened 2020-07-07 12:14 UTC
## Description

The preview doesn't show an image that is located in the parent folder.
I'm using asciidoctor-vscode v2.8.1

## Folder Structure

Logo.png
Folder/doc.asciidoc

## Preview

![image](https://user-images.githubusercontent.com/67958736/86778514-c1d87700-c05a-11ea-8e68-11c505e64d26.png)

**Comment by special946** [comment] 2020-07-16 08:37
I am using VScode version 1.46.1 - images are displayed.
After updating VScode to version 1.47.1, images stop showing.

**Comment by istavrakakis** [comment] 2020-09-02 11:52
Same for Visual Studio Code version 1.48.2

**Comment by Mogztter** [comment] 2021-05-11 22:05
I cannot reproduce this issue with Visual Studio Code version 1.56.1 and asciidoctor.asciidoctor-vscode 2.8.9

![work](https://user-images.githubusercontent.com/333276/117890465-7f547c00-b2b5-11eb-9b1d-e644ded32d56.PNG)

@istavrakakis @special946 @ulrichsch  Please test again with the latest version and provide additional information if it does not work

**Comment by SilentButeo2** [comment] 2021-06-09 18:23
Same here, but with image in the same folder.

Visual Studio Code version 1.56.2 and asciidoctor.asciidoctor-vscode 2.8.9

![image](https://user-images.githubusercontent.com/14175250/121408047-3baa6c00-c960-11eb-99ee-cc63dce2a623.png)

**Comment by Mogztter** [comment] 2021-06-10 08:04
@SilentButeo2 Could you please give us some information on your system? Are you using WSL2? Are you using Windows? Are files located on a shared/remote drive or on your local file system?

Could you try to create an HTML file with the following content:

```
<html>
  <body>
    <img src="test.jpg" alt="test">
  </body>
</html>
```

The, install the [HTML preview extension](https://marketplace.visualstudio.com/items?itemName=tht13.html-preview-vscode) and open/preview the HTML file.

Thanks!

**Comment by SilentButeo2** [comment] 2021-06-11 09:38
Working on plain Windows.
Files are on a simple folder.

Doing you test gives the first time:
![image](https://user-images.githubusercontent.com/14175250/121666252-550aff80-caa9-11eb-9aeb-a738df694489.png)

After putting security to Disable:
![image](https://user-images.githubusercontent.com/14175250/121666386-79ff7280-caa9-11eb-94af-d29b9c0438e1.png)

**Comment by SilentButeo2** [comment] 2021-06-11 10:04
extra info:
both online and inline (base64) images work
```
<html>
  <body>
    <img src="http://webgrabplus.com/sites/default/themes/WgTheme/images/slideshows/EPG_fading.jpg" alt="online"><br/>
    <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAO0AAABuCAMAAAD8t2TLAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAC1QTFRF////LVcpkauOZYdhrsStx9jF1uTV+//66PPn8vzy4uji7vft4O3f+P/38fPwC7dd6gAACdxJREFUeNrsXIti2yoMNYiHiSH//7kXCXD8AmTaddudta1zEht0QOhIgnSaHnnkkUceeeSRv1vszzRlv7OjL2hoUZEwTSHUNHIsoLYJ1oYBvE2tjnfu1Nw85DbNWCVAxysvgS7OgxEcR8vglfINtDJ1cxNuRaur7t1OTUfoSPtNM1GLKHqaBUk4aakBP+73plBC9XONrbP03opJWs3dG1FLoT6vVeqMtFeTBZFQkhYCbEILFS37es2Etq6W4up99dTSXUewmyvrduj8RFMaYauMNtD/8ro/sN+FdhlB2x3sEBJas5ujFZ2c/O61CGl0TKW/8E1oYfolaO0idpOVp3qdy5AuVrRzuqGy3hgG6H4J2jJHXWcmxNYGk6FGS07rXtrkp4plRzj6utklW353eA3DSzH0PnsflitXeyertiBV5FfioNyeJDTB1dSUthc4xL+z0q6n90A8gEzCoVxZYJSXH5BIsvgZtRN6w6tyBFJFq2kAeyFCmIbEah7lhn2AswEp87wrIQ0n2lLN/nSxm6+GCNf+j70GYoBjdvFMcryFZMlxM+DmCKRNdr4TIuhBtIHr35boOPTRUxxpSH/VM2a0S8eDqEG0qXnorwONftKeu1V5jhUPrWpqa3uD/0W0+fl+PHWIXfPcFkvOEQUXbe2+atD5PWhLKD/z0No9C5CbTsFyqMRPl5Zcd7oOoAnmS+vW2uwk+4Pi9JED14kmcjWy75MDeSk511gP/X5YTIsSk08eqRuEKRBx2v6gBNtMsB2PA4MP1NQsL1nEOmcWojq8pxcjzHcn1kCb3A7pc8u+OByI3UkypmuWoUULsERzx/lvxgjNG+rUxwlcdWetKF60n5MHX0lPs4sSnhRrBFTZr99Dmxtn5Imq4wfVjWZKsn+R+eV0wyX/3uPkm64qN86ILDhouc1AnVML9yf/Dp10+yYN5TH6YbSFmutoc22klvaXdPsu6ep2RPBx1r11q3l9q22yr2oKSZsXtmun2wMhhsFaol3ZLhwSzfmjRtN1AystIQpAlwuXaS727xflyaEAkrutZVGCF8pcPJ2qpZQ4+pDpbKKCIsxEoimhJKJshR8Bb2mXpIN3HhuxmXftoQUfiko4B1ExexUPJb6WfgAsWiGFUhikCMC4dy2eUrKwKRarVnElKqDmdkmawMRRoQDiSOHUY+zQKDI3lw3ggjblPJ7Ny7QElm1Oowo7ldqTSJW2eh/pcTAdKzaTkwAg3dkV6I0/1kUdfTfO5mV8mRYyWrCLONSIXXOlWAcdCiyZngGUnCDC8YbsoTbq3MuhmLXisCubFspb0eZ6oqy3M4bWnlhOHdS5lx93fVQJ49QW3nLY7XDFBDpR6E2026WhPkHjVp3vRZssB5+GTXbuM/V90lfRqfPrDinoHdr5XEnXG5tC71Sphahh8ilUnVyfhTU7TxZrwiZ9LXlllYCa+W0hSU1eCncr02u/K+KWooBave91ukWlzoFVixjpWTfbizT9k76W+ngr/218PqWkViZXkfPTFU0u3tKo2oCDHDTqYyuuhtoYSOd92mQO3pi5nb42ybyX/8aJRJK0h/zUfopvngwpZvPExbPWmt4IZrmg3LRFcRdu5ECgcM2g9PJJM5z/Zk63hxr2B2zun7gdfJxZkmgRl3rNQvCKEGcU0ZgSWBMGq6L9HEnv0/dC5vMebVj7WdEu+P5SyYH0ANroZp1hze042sOmWSHn8DHNK7TGpve9veZ2NYJWp6H1YfrFaOEYv21s8wqtn+wL33/Z67z8LtoUmtIQNo+6aMHIb7to1SGP3bS3JNsq/VhCG7KFn41Oj3GuTAbVzOVKpVxnrqg11MoIyKfvEjzvtulrHG/yvaWf4LWnmu5ifDinwXZw/1Zxn6K+G4OSU+N6OJ62eg95NeW6lpq3h/3fsq98PClGifRoxke9KI5RONz20vVewhL/NCJUediF1olE4hgutuzr68POi07kq9w+DR7fvy1JdHdyVfvoR4x/BdSt+cSRNoWIQUkUd/IN5XXAQTbfFScrZgF9bqPNuUstJTxzJKGFKRBYaU6erLym8zWfuRz0x3efbqMt+XDVSI4cmdL1yAf30IbwFbTlacm15NCuXYBjjmreMAhWcdCu3X5qKkNTm5/uLVybzpXWj/UsGe3C5WxfsnZCu5w4dF23CNYfd3MG122pu7sOWKIQ20hfZwWNomM+xSuPXO+nJcLFx+yxaLpyr9mN8VoCHYKLWna3mctpoanDp43893xDPkkUMteeKbSc5bLX79+nXOsSW3OqsM0yTD//Pd9g14J5bSuiwq2DnBt9hzT9MfI916A4+e/Fhq0uBfvr1mvxuRmrslrgnB7qO0LW/u55g3d/8texc6+xM6y5Rt11512SY6GFKppaRbyD9u7CZR77sz+C9lysbqO9e/Z8PTTOCy/NaF2qtjD1rkJ/LlY31y2o2zTEPNJVDuzaxue6VcatfJ45tey8VfPqcM5vY0ASffqyBj+sr0QBsxTdK+K2Nm59Y2M38WmqwNY+D7sqEm3gYk3ayRi5pf3lgCeIE6d3C+i8L0BRLDQQwShoVkPz6evQzkiXDdj8DSuVMlUM4kAaekOq7nerIgrgnCIY5DjH2Q2Tlk3Vu29Y0akGEj/5vMHUR8E+IXI/9+CdR+7tDR7PzsoUA4CzMqHVGbZmoGBM7iDaDnkFHpXDiWvpqDvgnuB9tIxvJA2iDe0wjBmmndHSdjbImFffQquZRD34HZzeyYFZcCxZHf2HWJDU8BgH7Ndtj025h3HU6HkH2azitveF8/HYo49HtzVryt2W6JJBLfRBdM7daQt8teU0IuFrn4cLPczVDa0K70hdZ/ozJEyPPPLII4888sgjjzzyyCOPPMKUfCBD8O5WeN9LpMJCvJbvCX+xAKbep2Qc/ki8qFZSdlO1MNc7iQVtAQP4gJQbtOuv6Yk3XPzKntHCyC9Ay5/bjPaFeOjHXza3IOCthTblmJGQ6+ULq5zidYEWvyoRp1aYD1qAV1wX8cl4Q/wUrzWdoEttxS7oWyo0x/T9EZEOi8bXKv5UP4NWRSWjKlK8UvkSFcqXEel7RVsqsIQWpIR3vE3u0cI7vixo4893fOCdgBDaV8Qau3vH1RKHFH/zDf7TsQuTuvkBSya0cb2+1rlNlzSV6nJuhXqLeIF/t2hxY/qV0b5wJD9HChAtUGtCKvGmniEPHPMA2zeipZlMaMtlHS3OBBC2HtrNb19roP1JL5UsGbLJCble7ix5ixafQpWNME200QCmdyqOb9FuLVli7/gVsR+15FfZjcGVlS+rXoomReZFnu++QnvwUgXtb/FSf4b8bh7+MXmRy9b/CFpctP/M1GKcKvX0yCOPPPLI/0P+E2AAA7JN+/OU8bgAAAAASUVORK5CYII=" alt="base64"><br/>
    <img src="test.jpg" alt="test"><br/>
  </body>
</html>
```

Gives:
![image](https://user-images.githubusercontent.com/14175250/121668950-1c205a00-caac-11eb-999d-d9054095c9ea.png)

**Comment by SilentButeo2** [comment] 2021-06-11 10:09
Don't know if this is a vscode issue.
But a quick search broth me to 
https://github.com/tht13/html-preview-vscode/commit/dbd3262d4af340a83d6f73a12a7f55c28fa3ca0f
If this part of the code is used for the preview, the image should start with a /

**Comment by MartinBucher** [comment] 2021-06-14 12:12
I have the same problem with images not showing in the preview. (Windows 10, Visual Studio Code v1.57.0, asciidoctor.asciidoctor-vscode v2.8.9)
What I figured out is that, if the AsciiDoc source file have a space in the file name the image wont show in the preview
* "ImageTest.adoc" -> preview works as expected
* "Image Test.adoc" -> image is not shown in the preview

**Comment by SilentButeo2** [comment] 2021-06-14 12:24
Ok, it will not be the source file name, but the full path.
Because my file doesn't have spaces, but the full path does.

**Comment by maventis** [comment] 2021-06-14 12:30
> Ok, it will not be the source file name, but the full path.
> Because my file doesn't have spaces, but the full path does.

Yes, I can repro this as well if I have spaces in the path.

**Comment by pgw333** [comment] 2021-08-19 11:16
I needed to remove not only spaces from a path, but also the underscore "_" from a file name.

**Comment by alexmakar831** [comment] 2021-10-06 17:32
If I delete space in *.adoc file name, then OK

**Comment by apupier** [comment] 2023-08-17 14:50
I tried with VS Code AsciiDoc 3.1.3 and it is working for me with space in both path and name:

![image](https://github.com/asciidoctor/asciidoctor-vscode/assets/1105127/f76fdf94-3424-4972-8868-91fd26c2af61)

Can someone on Windows tries to reproduce too?

**Comment by ulrichsch** [comment] 2023-08-18 04:42
I tested on Windows with VS Code AsciiDoc 3.1.3.

Again with folder structure:

`c:/tmp/Logo.png`
`c:/tmp/Folder/test.adoc`

and test.adoc:

`image:../logo.png[]`

It works fine if VS Code was opened on c:/tmp.  
But it doesn't if it was opened on c:/tmp/Folder

**Comment by ggrossetie** [comment] 2024-03-09 16:05
> It works fine if VS Code was opened on c:/tmp.
> But it doesn't if it was opened on c:/tmp/Folder

@ulrichsch That's the behavior described in #848 but I don't think it's related to spaces in path.

I cannot reproduce this issue on Windows. As long as the image is inside the workspace it's working.

Please provide a screencast or a step by step reproduction case.

**Comment by ulrichsch** [comment] 2024-03-12 07:16
@ggrossetie You exactly described the issue. 
* If I opened the vscode on c:\tmp the image is in the workspace and the preview is working. 
* If I opened the vscode on c:\tmp\Folder the image is **NOT** in the workspace and the preview is **NOT** working.

**Comment by ggrossetie** [comment] 2024-03-12 09:56
Closing as duplicate since https://github.com/asciidoctor/asciidoctor-vscode/issues/848 more accurately describes the issue.

**Closed by ggrossetie** 2024-03-12 09:56 UTC
Labels: 🐞 bug, 👁️ area/html-preview
