### ISSUE TITLE
No autoscroll in VSCode > 1.28

### ISSUE THREAD

**Issue by slo-sleuth** [asciidoctor/asciidoctor-vscode#182] opened 2019-04-11 19:34 UTC
The following Preview settings are inoperable in v2.4.0: 
- scroll editor with preview
- scroll preview with editor

Also, with the default "Use_asciidoctor_js", the table lines are not visible and table rows are separated by greater space than normal.  This is true in light or dark themes.  Reverting to asciidoctor_command or v2.3.3 fixes.

Thanks.

**Comment by MatteoCampinoti94** [comment] 2019-04-16 21:42
The issues with the preview style have been fixed with the latest commits, we'll be publishing the next release soon :)

We're still investigating the problem with the scrolling though, still unsure what causes it.

**Comment by slo-sleuth** [comment] 2019-04-19 21:04
If it helps, the issue occurs in later versions of VS Code and not earlier.  The preview styles and scrolling worked properly in VS Code 1.28 with AsciiDoc extension v2.5.0.  Same extension with VS Code v1.33.1 loses auto scrolling.

Confirmed that preview style is corrected in v2.5.0 with VS Code v1.33.1, thank you.

Version: 1.33.1 (system setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Comment by MatteoCampinoti94** [comment] 2019-04-19 21:40
Style issue was actually our fault, we forgot to change a setting when we removed contribution points from the extension. Removing the code that handled those triggered an old IF that was laying around unused which broke styling. Kind of a freak coincidence really x3

I noticed that the autoscrolling was broken by VSCode yeah. Been looking at its code while working on release 2.5.1, but couldn't find the problem. It's not an error or it would turn up in the dev console, really weird. Same thing happens with folding and outline, the code should work but for some reason it won't.

**Comment by DanielSWolf** [comment] 2019-05-13 10:49
Has there been any progress on the autoscroll problem?

**Comment by MatteoCampinoti94** [comment] 2019-05-13 11:26
Not yet, we are focusing on a code overhaul and on small updates at the moment.

**Comment by chuck-confluent** [comment] 2019-05-16 16:24
I'd like to chime in that I'm on VScode version 1.33.1 and autoscroll works when I do the following:
- Install version extension version 2.3.3
- reload VScode

Scrolling works, but curiously when I check extensions, it says I'm using version 2.7 even though I am clearly not (styling a formatting is slightly uglier in the older version).

All this is to say that it's not *just* an issue with newer VScode version since the older extension still scrolls. It must be a combination of something that changed in the new extension version after 2.3.3 and something that changed in VScode. I hope this helps! I love the extension and look forward to this feature being fixed!

**Comment by MatteoCampinoti94** [comment] 2019-05-16 22:32
Thanks for spotting that @chuck-confluent! I will look deeper into the 2.4.0 code to spot the guilty change and reverse it if possible.

**Comment by joaompinto** [comment] 2019-05-22 07:49
@MatteoCampinoti94 I will be looking into this today, relax :)

**Comment by MatteoCampinoti94** [comment] 2019-05-22 07:51
Thank you @joaompinto :heart: ^.^

**Comment by joaompinto** [comment] 2019-05-22 08:29
There is a "console.log("GOT MESSAGE", event.data);"  which is producing no output on the "Web View: Developer Tools", which means the javascript associated with the preview window is not being properly execute.

Installing v2.3.3 from the extension works, building and running it from a current VSCode does not work. The difference is that when running from the source, the webview related .js files are rebuilt (from the .ts files). 

I need to investigate further.

**Comment by joaompinto** [comment] 2019-05-22 10:50
Found the root cause, the preview HTML was expected to include index.js script (which provides the scroll code to the webview with this code:

```js
${this.getScripts(nonce)}
```

The getScripts() is looking for the scripts in "contributions"

```js
private getScripts(nonce: string): string {
 		return this.contributions.previewScripts
}
```
This contribution point is no longer available, it was removed on commit:
https://github.com/asciidoctor/asciidoctor-vscode/commit/0322d8805c3afd53e5422ed6fe0b4ef591da27ef

When I have removed the contribution points from the configuration I was not fully aware of their purpose, that is the cost of reusing a lot of 3rd party code :(

VSCode's markdown preview (from which our code was borrowed) is bundled in 2 extensions:
extensions/markdown-basics and ./extensions/markdown-language-features, as such, they inherently need contribution points for integration each other's configuration.

For our case contribution points are not needed, but we need to make sure that the configuration that was  provided from  them, is now available somewhere :P

**Comment by MatteoCampinoti94** [comment] 2019-05-22 10:54
I knew removing the contribution points would come back to haunt us xD

For the stylesheets I resolved it using the extension location:
```typescript
private ext_path = vscode.extensions.getExtension('joaompinto.asciidoctor-vscode').extensionPath;
    private stylesdir = path.join(this.ext_path, 'media')
```

**Comment by MatteoCampinoti94** [comment] 2019-05-22 11:08
I didn't notice the `AsciidocContributions` interface when I made that, I'll switch to that for the styles, use `getExtension()` for `extensionPath` and then `path.join()` for all the other files.

**Comment by MatteoCampinoti94** [comment] 2019-05-22 11:12
We could recover the code deleted in 0322d88 and just use those two methods, converting to `vscode.Uri` where needed.

**Comment by joaompinto** [comment] 2019-05-22 11:46
Your approach to get the path to the resource is OK. I have applied to the index.js in my local code.
Now I am getting _Failed to load resource: net::ERR_ACCESS_DENIED_ on the .js resources which is most likely related to the web view security settings.

**Comment by MatteoCampinoti94** [comment] 2019-05-22 12:02
Great x3
I remember doing some changes to the security settings some time ago, to make them distinct from Markdown's.

**Comment by joaompinto** [comment] 2019-05-22 12:25
This ERR_ACCESS_DENIED does not seem to be related to the CSP settings, as that triggers a different kind of error, and also because the current CSP is set to accept our specific js inclusion.

![asciidoctor-vscode-denied](https://user-images.githubusercontent.com/1143125/58173976-afec1700-7c94-11e9-8570-a524f09ed8de.png)

I am not able to find much information about this error, a similar issue is report at https://github.com/Microsoft/vscode-extension-vscode/issues/158 , but there was no answer.

**Comment by joaompinto** [comment] 2019-05-22 12:38
Found the reason after reading https://github.com/Microsoft/vscode/issues/47634 .

The "ERR_ACCESS_DENIED" is happening because the path to the .js uses a "vscode-resource:" which validates that the path is within "localResourceRoots" . Again, the current code is setting localResourceRoots by looking at the missing "contribution" point paths.

**Comment by joaompinto** [comment] 2019-05-22 17:56
The current code "master" code fixes the webclient .js loading, now the issue is at the extension side, the "data-line-NN" which relates html elements to the adoc source is missing, something changed within the ascidoc parser helper. Needs further investigation.

**Comment by joaompinto** [comment] 2019-05-22 18:34
I have spent a significant amount time researching for the small piece of code which provides the line info meta data and which is no longer working, I have a limited experience with Ruby/Javascript so I have filled an issue  https://github.com/asciidoctor/asciidoctor.js/issues/731 with the hope that we get a quicker and more reliable fix.

**Comment by MatteoCampinoti94** [comment] 2019-05-22 18:44
Could you maybe make a branch with your edited code?

**Comment by joaompinto** [comment] 2019-05-22 19:07
I did not touch the code on this regard yet (the "blocksWithLineNumber" component), but on the asciidoctor.js issue I am providing a full .js sample that is sufficient for testing. You can run it using "node" from some dir «after installing asciidoctor to it with npm»

**Comment by MatteoCampinoti94** [comment] 2019-05-22 19:18
Okay :+1:

**Comment by joaompinto** [comment] 2019-05-23 21:38
I believe the latest commit on master fixed the issue, it works fine on my machine. However because this was a complex fix I am attaching the asciidoctor-vscode-2.7.4.vsix and I would appreciate some testing feedback.

[asciidoctor-vscode-2.7.4.vsix.zip](https://github.com/asciidoctor/asciidoctor-vscode/files/3214262/asciidoctor-vscode-2.7.4.vsix.zip)

**Comment by rocketraman** [comment] 2019-05-23 23:41
@joaompinto  Tried out 2.7.4 using the vsix above and autoscroll now works again.

**Comment by danyill** [comment] 2019-05-24 00:30
@joaompinto Also tried using the vsix and joyfully autoscroll works again, thanks for this 😄

**Comment by joaompinto** [comment] 2019-05-24 08:25
Fix published to the marketplace. Thanks all for the help :)

**Closed by joaompinto** 2019-05-24 08:25 UTC
Labels: bug

**Comment by MatteoCampinoti94** [comment] 2019-05-25 10:20
Fantastic @joaompinto!
