### ISSUE TITLE
can use different icons for different levels

### ISSUE THREAD

**Issue by dikinova** [asciidoctor/asciidoctor-vscode#566] opened 2022-04-14 07:29 UTC
if we use different icons for titles of different levels in the outline panel, we will get information about level of titles easily.

for example, if we have an adoc file:

-----

= title1

== title2

=== title3

==== title4

-----

then in the outline panel we show:

------
[a] title1
	[ab] title2
		[abc] title3
			[abcd] title4

------

note: there are 4 different icons: [a],[ab],[abc],[abcd]

**Comment by Mogztter** [comment] 2022-04-14 09:39
That's a duplicate of https://github.com/asciidoctor/asciidoctor-vscode/issues/525
I've already mentioned why it's not possible: https://github.com/asciidoctor/asciidoctor-vscode/issues/525#issuecomment-1053558601

**Closed by Mogztter** 2022-04-14 09:39 UTC
