### ISSUE TITLE
Extension called process.exit() and this was prevented by Visual Studio code

### ISSUE THREAD

**Issue by GoGoris** [asciidoctor/asciidoctor-vscode#89] opened 2018-05-23 06:47 UTC
The following stacktrace is printed in the dev tools when this extension loads:
```
Error: An extension called process.exit() and this was prevented.
	at Object.process.exit (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:738:510)
	at String.$$exit [as $exit] (C:\Users\USER2869\.vscode\extensions\joaompinto.asciidoctor-vscode-0.12.0\node_modules\opal-runtime\src\opal.js:4041:12)
	at getNativeStringProperties (c:\Program Files\Microsoft VS Code\resources\app\extensions\markdown-language-features\node_modules\string\lib\string.js:726:32)
```

**Comment by danyill** [comment] 2020-02-29 06:19
@GoGoris are you able to reproduce this error?

It seems to have come from Opal (which is used to build Asciidoctor.js) and vscode and Asciidoctor have both been changed quite a bit since this bug was filed.

If we can't reproduce I'm thinking of closing this issue.

**Comment by danyill** [comment] 2020-03-06 19:18
Closing in the absence of feedback -- feel free to re-open this issue if you are able to confirm it still occurs.

**Closed by danyill** 2020-03-06 19:18 UTC
Labels: bug
