### ISSUE TITLE
Underline not rendered in preview

### ISSUE THREAD

**Issue by maddes-b** [asciidoctor/asciidoctor-vscode#511] opened 2022-02-05 12:01 UTC
## Description

Underlined text is not rendered in preview.

## System Information

Version: 1.64.0 (user setup)
Commit: 5554b12acf27056905806867f251c859323ff7e9
Date: 2022-02-03T04:22:20.678Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044

Extension: asciidoctor.asciidoctor-vscode v2.9.3

## To Reproduce

```
I should be [.underline]#underlined#, am I?
Like mentioned in https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/#text-formatting
```
## Screenshots & Files

![image](https://user-images.githubusercontent.com/565223/152641211-e3489951-c828-40a8-be6f-4d24c09afc66.png)

**Comment by Mogztter** [comment] 2022-02-05 17:19
I think it's a duplicate of #501 
It's working fine on Linux:

![image](https://user-images.githubusercontent.com/333276/152651851-075a8778-3353-400f-8876-1bf1146f04de.png)

**Closed by Mogztter** 2022-02-05 17:19 UTC
Labels: 👀 investigating

**Comment by maddes-b** [comment] 2022-02-06 13:49
Thanks for the analysis. Will re-check in 2.9.4, when released.

**Comment by maddes-b** [comment] 2022-02-06 13:54
Just recognized it is already released, and underline is working again in Windows version of VS Code. Thanks.
