### ISSUE TITLE
Preview does not work with remote GitHub repository (via extension GitHub Repositories)

### ISSUE THREAD

**Issue by gem-cp** [asciidoctor/asciidoctor-vscode#563] opened 2022-04-08 07:45 UTC
## Description

I use the extension GitHub repositories which uses a virtual filesystem in memory. The asciidoc preview seems not to work for asciidoc files in this virtual file system.

## To Reproduce

1. Install GitHub repositories extension
2. Install asciidoc extension
3. Open a remote repository with the GitHub Repositories: Open Repository... command
4. Open or create a new adoc file from the repository
5. Open the asciidoc preview

**Comment by Mogztter** [comment] 2022-04-08 08:03
I cannot reproduce this issue. Did you "Trust this folder"?
Open the "Extensions" panel, search the "AsciiDoc" extension, click on the shield/lock icon:

![image](https://user-images.githubusercontent.com/333276/162392386-b5b19865-30a1-4f5c-a773-b8b7fd5d5a14.png)

It should open a new tab "Workspaces Trust":

![image](https://user-images.githubusercontent.com/333276/162392472-989d9ccd-e194-48a0-bfd1-4c150b817db5.png)


Click "Trust", it should enable the extension.

**Comment by danyill** [comment] 2022-06-06 09:10
Closing due to lack of follow up information.

**Closed by danyill** 2022-06-06 09:10 UTC
Labels: ❔ question, 👀 investigating
