### ISSUE TITLE
"TypeError: range must be set" when previewing

### ISSUE THREAD

**Issue by chuck-confluent** [asciidoctor/asciidoctor-vscode#364] opened 2020-09-16 18:46 UTC
## Description

New behavior today -- When I try to preview an adoc, I get an error:

```
TypeError: range must be set

Source: AsciiDoc (Extension)
```

I uninstalled/reinstalled and the issue persists.

## System Information

Version: 1.49.0 (user setup)
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-10T13:22:08.892Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

## To Reproduce

Select the asciidoc preview icon for an adoc.

**Comment by chuck-confluent** [comment] 2020-09-16 20:21
I will add that I'm using ubuntu 18.04 on Windows Subsystem for Linux WSL2

**Comment by chuck-confluent** [comment] 2020-09-16 20:51
My colleague does not have the issue and is running vs code 1.39. This might mean it's this latest vs code 1.49 that is causing the issue

**Comment by chuck-confluent** [comment] 2020-09-16 21:06
I rolled back to vs code 1.48.2 and the issue disappeared. I suppose that means vs code 1.49.0 is the culprit

**Comment by henrietteBaum** [comment] 2020-09-18 09:23
I habe the same problem on mac-os. The error message occurs when I use the line
`:source-highlighter: rouge` (no matter, which one I chose)
use. The preview will then show nothing at all. As soon as I delete the line it will work normally again.

## Systeminformation: 
Version: 1.49.1
Commit: 58bb7b2331731bf72587010e943852e13e6fd3cf
Datum: 2020-09-16T23:21:17.533Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
Betriebssystem: Darwin x64 19.6.0

**Comment by softwaredoug** [comment] 2020-09-20 15:01
I'm also having this issue suddenly. My previews don't work in AsciiDoc. However if I comment out the source-highlighter it works.

Information on VS Code:

```
Version: 1.49.1
Commit: 58bb7b2331731bf72587010e943852e13e6fd3cf
Date: 2020-09-16T23:21:17.533Z (3 days ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```

Here's my source code for what I'm starting writing.

```
= AI-Powered Search
:chapter: 11
:sectnums:
:figure-caption: Figure {chapter}.
:listing-caption: Listing {chapter}.
:table-caption: Table {chapter}.
:sectnumoffset: 9
:leveloffset: 1
:xrefstyle: short
:stem: latexmath
:source-highlighter: coderay
:bibliography-database: dl4nlp.bib
:bibliography-style: ieee

= Automated Learning to Rank
```

I also had this issue in 1.49.0

**Comment by Leon0402** [comment] 2020-09-20 15:42
Same here!

**Comment by cunka** [comment] 2020-09-22 13:07
Have the same issue in 1.49.1
Preview does not work and get the "TypeError: range must be set" message.

**Comment by ericodex** [comment] 2020-09-23 18:20
same issue here.

Version: 1.49.1 (user setup)
Commit: 58bb7b2331731bf72587010e943852e13e6fd3cf
Date: 2020-09-16T23:27:51.792Z (6 days ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by istavrakakis** [comment] 2020-09-28 12:16
Same with VSC 1.49.2, and MacOS Catalina 10.15.7

**Comment by rschuetzler** [comment] 2020-09-28 22:46
I get the same error even when not previewing. Removing the `source-highlighter` line in the header fixes it.

Version: 1.49.2
Commit: e5e9e69aed6e1984f7499b7af85b3d05f9a6883a
Date: 2020-09-24T16:23:52.277Z (4 days ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

**Comment by armakunizen** [comment] 2020-09-29 07:22
You can get this error on Windows too. I got this with an ADOC file where the :stylesdir: or the :stylesheet: point to nonexistent folder or file.

**Comment by istavrakakis** [comment] 2020-09-29 07:27
Is it possible that the cause can be so many different attributes?
This is really weird..
I wish someone could check that.
---------------------------------
Ioannis Stavrakakis
Senior Technical Writer

| m: +30 6976568788

| e: istavrakakis@omilia.com

| w: www.omilia.com
<https://www.omilia.com/>

**Comment by engelben** [comment] 2020-09-29 13:59
I am getting the same issue. In my case it seems to be the same as @armakunizen, ie a reference to an unresolved stylesheet path.

**Comment by aucampia** [comment] 2020-09-30 20:27
For me this happened when I referred to a non existing image.

**Comment by lutopastialis** [comment] 2020-10-01 10:11
I also had this issue maybe 2 months ago along with some of my team mates. I'm always keen to have the latest versions of the tools I'm using, so the first thing I did, when I encountered this issue, was updating all my tools. Here are my current versions of everything relevant:

## infrastructure

### vscode
```
Version: 1.49.2 (user setup)
Commit: e5e9e69aed6e1984f7499b7af85b3d05f9a6883a
Date: 2020-09-24T16:29:41.983Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.17763
```

### vscode plugins
```
asciidoctor.asciidoctor-vscode v2.8.3
```

### packages
We use chocolatey and rubygems for installing everything relevant for asciidoc/vscode, so I updated those to the latest versions, which are (I'm not listing all the package dependencies, but I use the standard install commands for choco and ruby without any additional options, meaning the dependencies are also the latest):

#### choco
```
chocolatey 0.10.15
chocolatey-core.extension 1.3.5.1
ruby 2.7.1.1
```

#### ruby gems
```
asciidoctor (2.0.10)
asciidoctor-pdf (1.5.3)
coderay (1.1.3, 1.1.2)
prawn-svg (0.30.0)
rouge (3.23.0, 3.21.0, 3.18.0)
```

## settings
Some relevant settings.

### vscode
```
"asciidoc.use_asciidoctorpdf": true,
"asciidoc.preview.fontSize": 13,
"asciidoc.preview.lineHeight": 1.3,
"[asciidoc]" : {
	"editor.rulers": [80]
},
"workbench.colorCustomizations": {
	"editorRuler.foreground": "#ff4081"
},
"asciidoc.enableErrorDiagnostics": false,
"asciidoc.preview.refreshInterval": 10000,
"asciidoc.use_asciidoctor_js": true
```

## document
These are the asciidoc labels and references in the main document that I want to preview:
```
include::../asciidoc/templates/doc_template_header.adoc[]

:revnumber: 0.1
:description: Foo bar.
:keywords: foo, bar, baz
```

Content of the referenced header template file:
```
:organization: Foo
:docdate: 
:doctype: book
:source-highlighter: rouge
:imagesdir: resources/images
:logodir: logo
:diagramsdir: resources/diagrams
:chapter-label:
:sectnums:
:sectnumlevels: 5
:toc: right
:toclevels: 3
:xrefstyle: short
:stylesheet: ../asciidoc/resources/css/clean.css
:icons: font
ifdef::backend-pdf[]
:pdf-theme: bar
:pdf-themesdir: ../asciidoc/resources/theme
:title-logo-image: image:../../../asciidoc/resources/{logodir}/My-Logo_1c-black.svg[pdfwidth=75%,align=center]
endif::[]
```

## what solved it for me
After updating everything to the latest version and some research I turned off the asciidoc rendering with javascript by setting
```
"asciidoc.use_asciidoctor_js": true
```
to `false`, then closing the asciidoc doc, restarting vscode and then opening the document again. The preview worked again, but with the limitations of not using javascript rendering. After turning javascript rendering back on the problem was solved and hasn't returned since.

My collegues weren't so lucky, my remedy did not work for them, although I do not know what versions they currently use. They report that removing of the line `:source-highlighter: rouge` from the header template solves the issue for them. I did some research about the ruby gem `rouge` and found out that it does more or less the same as `pygments.rb`, which I originally had installed next to `rouge`. I uninstalled `pygments.rb` for it seemed redundant to `rouge` and I did not find any impacts on the asciidoc preview feature.

**Comment by Dieter-W** [comment] 2020-10-01 11:20
Hi, I had the same error.
After deleting the` :source-highlighter: rouge` tag all worked

**Comment by edl7878** [comment] 2020-10-08 02:47
:data-uri: can also introduce this problem in some documents.

**Comment by marcdexet-cnrs** [comment] 2020-10-10 09:04
Hi.

Same problem here

VsCode:  1.49.2
Asciidoc extension: 2.8.3
OS: Ubuntu 18.04.4 LTS

When I comment `:source-highlighter: `, message is off.

**Comment by marcdexet-cnrs** [comment] 2020-10-10 09:10
> Hi.
> 
> Same problem here
> 
> VsCode: 1.49.2
> Asciidoc extension: 2.8.3
> OS: Ubuntu 18.04.4 LTS
> 
> When I comment `:source-highlighter: `, message is off.

I update to VS code 1.50.0, I still get the same problem.

**Comment by danyill** [comment] 2020-10-11 06:35
I think the issue is caused by the (very helpful) new diagnostic error information added in https://github.com/asciidoctor/asciidoctor-vscode/pull/329. 

As a short term workaround, disabling this diagnostic error in user settings prevents the error from occurring:

![image](https://user-images.githubusercontent.com/674783/95671891-57eee100-0bf8-11eb-9334-1d990dc19a32.png)

I'm not sure why this error has only begun now. I'll try to dig into it a little.

**Closed** 2020-10-11 12:30 UTC
