### ISSUE TITLE
UNDEFINED at bottom of each PDF pag

### ISSUE THREAD

**Issue by Johan1974** [asciidoctor/asciidoctor-vscode#543] opened 2022-03-07 07:58 UTC
This is an example issue. Use just the headings and fill out all necessary information. Screenshots & Files and Additional Context are optional.

## Description

Hello,

I notice nowadays in my converted PDF a text UNDEFINED at the center bottom of each page.

I tried with older versions and noticed this error occured after version 2.8.9

Is there some parameter i need to set to make this text go away? 

Thanks!

Johan

## System Information

Version: 1.65.0 (user setup)
Commit: b5205cc8eb4fbaa726835538cd82372cc0222d43
Date: 2022-03-02T11:12:08.962Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044

## To Reproduce

Generate PDF. Also an empty page is generating UNDEFINED at the bottom so it is nothing to do with the syntac being used it seems.

## Screenshots & Files

![image](https://user-images.githubusercontent.com/8274075/156990616-5abe935c-db52-4575-b164-a5cc619fce40.png)

If applicable, add screenshots to help explain your problem. If the problem occurs only in a specific file, attach the file to the issue (do not copy the contents here).

## Additional Context

Error appears after version 2.8.9

**Comment by Mogztter** [comment] 2022-03-07 11:01
This is a duplicate of: https://github.com/asciidoctor/asciidoctor-vscode/issues/526
It was fixed in https://github.com/asciidoctor/asciidoctor-vscode/issues/526 and will be available in the next release.

**Closed by Mogztter** 2022-03-07 11:01 UTC

**Comment by Johan1974** [comment] 2022-03-07 14:30
Thanks,

When will the new release available ?

**Comment by Mogztter** [comment] 2022-03-07 19:35
We've just released: https://github.com/asciidoctor/asciidoctor-vscode/releases/tag/v2.9.8
