### ISSUE TITLE
Preview doesn't work "not found"

### ISSUE THREAD

**Issue by michaelTrivum** [asciidoctor/asciidoctor-vscode#273] opened 2020-02-21 09:31 UTC
I trying to start preview with hotkeys on mac

## Description

command 'extensible.markdown.showPreview' not found

command 'extensible.markdown.showPreview' not found

## System Information

VS Code: Version: 1.42.1
Extension: v2.7.13
MacOS Catalina: 10.15.2

## To Reproduce

Steps to reproduce the issue:

Toggle Preview - ctrl+shift+v (Mac: cmd+shift+v)
Open Preview to the Side - ctrl+k v (Mac: cmd+k v)

best regard
Michael

**Comment by danyill** [comment] 2020-02-29 00:45
@michaelTrivum thanks for reporting.

We seem to see this error from time to time and either after restarts of the machine/desktop environment or vscode it seems to go away (and it's current unclear why). Is this still a problem for you? If so we could look into retrieving some logs to diagnose it further.

**Comment by michaelTrivum** [comment] 2020-03-02 13:13
unfortunately yes, I have never been able to use the preview feature :(

**Comment by neillrobson** [comment] 2020-03-02 17:52
I also experience this issue, or a very similar one. The error that I receive is as follows:

```
command 'markdown.extension.togglePreviewToSide' not found
```

This output leads me to believe that the issue is a keyboard shortcut conflict between this Asciidoc extension and whatever Markdown extension that @michaelTrivum and I use. The preview opens just fine when using the Command Palette (`ctrl-shift-p` followed by `AsciiDoc: Open Preview to the Side`). 

Steps that I have yet to try are reassigning the shortcut and disabling the Markdown extension that I use (namely [Markdown All-in-One](https://github.com/yzhang-gh/vscode-markdown)).

**Comment by danyill** [comment] 2020-03-02 18:29
@michaelTrivum are you able to use this feature from the command palette?

**Comment by kogiokka** [comment] 2020-04-04 17:25
If it's not  caused by keyboard shortcut conflict as mentioned above, there is another possible workaround: Enter the [extensions folder](https://code.visualstudio.com/docs/editor/extension-gallery#_common-questions) and remove `joaompinto.asciidoctor-vscode-<version>` directory. Install the extension again from the marketplace.

I had similar problem. The command doesn't work from command palette, either. It's fix after I remove the extension completely and install it again.

**Comment by joaompinto** [comment] 2020-06-27 09:12
The extensible.markdown.showPreview is not a command provide by this extension, another extension is taking over the key binding. You might be able to find the extension the error follow this procedure:
> View -> Output 
In the combobox where you have "Tasks"  select "Log (Extension Host)", this log may show the error and the related extension.

I am closing this issue as it does not seem to be related to this extension.

**Closed by joaompinto** 2020-06-27 09:12 UTC

**Comment by jonathan-s** [comment] 2023-07-26 10:35
I've got the following version of vscode

Version: 1.80.0
Commit: 660393deaaa6d1996740ff4880f1bad43768c814
Date: 2023-07-04T13:39:33.766Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 22.2.0

And I'm getting this error in the output.
Has something changed on the vscode side perhaps, @joaompinto ? 

```
2023-07-26 12:33:14.926 [error] Error: command 'vscode.previewHtml' not found
    at e.$Zvb.k (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1508:12243)
    at e.$Zvb.executeCommand (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1508:12172)
```

**Comment by chevdor** [comment] 2023-09-05 12:51
I ran into the same issue while having https://marketplace.visualstudio.com/items?itemName=bcherny.better-asciidoc-vscode also installed. After removing that one, the default Asciidoc extension preview did work.

**Comment by ggrossetie** [comment] 2023-09-05 18:37
Might be something to add in a "Troubleshoots" / "Common errors" section. If someone wants to contribute this section in the README I would gladly merge it.

**Comment by ivan1602** [comment] 2024-12-02 09:36
> I ran into the same issue while having https://marketplace.visualstudio.com/items?itemName=bcherny.better-asciidoc-vscode also installed. After removing that one, the default Asciidoc extension preview did work.

This also worked for me!
