### ISSUE TITLE
Latest release (3.4.0) returns an error regarding ripgrep which I did not have with a local install

### ISSUE THREAD

**Issue by alaindresse** [asciidoctor/asciidoctor-vscode#912] opened 2024-10-11 10:43 UTC
@ggrossetie : Latest release (3.4.0) returns an error regarding ripgrep which I did not have with a local install.

```
2024-10-11 12:39:17.817 [error] Error: spawn Unknown system error -8
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at spawn (node:child_process:795:9)
    at /Users/alaindresse/.vscode/extensions/asciidoctor.asciidoctor-vscode-3.4.0/src/util/findFiles.ts:26:21
    at new Promise (<anonymous>)
    at ripgrep (/Users/alaindresse/.vscode/extensions/asciidoctor.asciidoctor-vscode-3.4.0/src/util/findFiles.ts:25:10)
    at findFiles (/Users/alaindresse/.vscode/extensions/asciidoctor.asciidoctor-vscode-3.4.0/src/util/findFiles.ts:18:25)
    at findAntoraConfigFile (/Users/alaindresse/.vscode/extensions/asciidoctor.asciidoctor-vscode-3.4.0/src/features/antora/antoraDocument.ts:20:43)
    at getAntoraConfig (/Users/alaindresse/.vscode/extensions/asciidoctor.asciidoctor-vscode-3.4.0/src/features/antora/antoraDocument.ts:87:33)
    at getAttributes (/Users/alaindresse/.vscode/extensions/asciidoctor.asciidoctor-vscode-3.4.0/src/features/antora/antoraDocument.ts:101:30)
    at AntoraSupportManager.getAttributes (/Users/alaindresse/.vscode/extensions/asciidoctor.asciidoctor-vscode-3.4.0/src/features/antora/antoraContext.ts:142:27)
    at AsciidocEngine.convertFromTextDocument (/Users/alaindresse/.vscode/extensions/asciidoctor.asciidoctor-vscode-3.4.0/src/asciidocEngine.ts:161:50)
    at AsciidocContentProvider.providePreviewHTML (/Users/alaindresse/.vscode/extensions/asciidoctor.asciidoctor-vscode-3.4.0/src/features/previewContentProvider.ts:16:22)
    at AsciidocPreview.doUpdate (/Users/alaindresse/.vscode/extensions/asciidoctor.asciidoctor-vscode-3.4.0/src/features/preview.ts:388:32)
```

**Comment by ggrossetie** [comment] 2024-10-11 11:33
Can you copy/paste the "About"? Are you doing something special?
I cannot reproduce on my machine:

```
Version: 1.94.0
Commit: d78a74bcdfad14d5d3b1b782f87255d802b57511
Date: 2024-10-02T13:08:12.626Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Linux x64 5.19.0-46-generic
```

**Comment by alaindresse** [comment] 2024-10-11 12:43
Version: 1.94.2 (Universal)
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
Date: 2024-10-09T16:08:44.566Z (1 day ago)
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0

**Comment by alaindresse** [comment] 2024-10-11 13:14
@ggrossetie  I uninstalled the extension, restarted my computer, reinstalled, and seems to be working.

**Comment by ggrossetie** [comment] 2024-10-11 15:05
It’s reassuring, maybe some kind of conflicts since you've installed a local copy and play with `ripgrep` on your machine? Can we close this issue?

**Comment by alaindresse** [comment] 2024-10-11 21:42
Ok after reboot computer

**Closed** 2024-10-11 21:43 UTC
Labels: 🐞 bug
