### ISSUE TITLE
File used by another process error

### ISSUE THREAD

**Issue by mgroves** [asciidoctor/asciidoctor-vscode#100] opened 2018-07-25 19:43 UTC
I generally write asciidoc and the code samples at the same time. I write my code in Visual Studio and my asciidoc in Visual Studio Live. I often include snippets of code using the include directive:

```
[source,C#,indent=0]
----
include::src/DistributedCachingExample/Startup.cs[tag=AddCouchbase]
----
```

I don't know when this behavior started, but it seems that using asciidoctor-vscode locks up the source code files that I'm including. If I try to update a Startup.cs in Visual Studio, for instance, I get an error message "The process cannot access the file ... because it is being used by another process."

Is there a recent change that locks up anything that I `include` from the asciidoc file? Or maybe a recent change in VSCode that causes this? This has become a big hassle, because I have to close Visual Studio Code, save changes in Visual Studio, and reopen Visual Studio Code every time I make a change (during writing and editing something code heavy, this is quite often).

Is there any known workaround? Is there something I'm doing wrong? It didn't seem like this was always the case.

**Comment by jvalkeal** [comment] 2019-05-26 07:18
I'll bet a root cause for this is same as in #203 I just opened. Extension never releases those opened includes and in windows this is even bigger problem due to ways windows can lock opened files.

**Comment by jvalkeal** [comment] 2019-05-27 14:06
@mgroves When 2.7.5 is released could you check if that fixes your issues? It possibly doesn't fix an underlying issue that `asciidoctor.js` do lock a files in windows but if file descriptors are closed immediately then you should not get in trouble anymore. I remember in my previous life as a windows user I always had to track down processes stealing files handles.

**Comment by mgroves** [comment] 2019-05-28 00:01
Yes, I will check it out! Would you mind commenting here when that release happens, so I don't forget?

**Comment by jvalkeal** [comment] 2019-05-30 08:47
I think 2.7.5 is already released. At least vscode code shows that version.

**Comment by mgroves** [comment] 2019-05-30 20:02
My initial checks show that it's working fine now! I'm not able to make the "The process cannot access the file" error happen. Hopefully this matches up with what you're seeing with your own tests. Thank you :)

**Comment by danyill** [comment] 2020-02-14 01:33
Thanks for reporting. It looks like this issue has been fixed upstream so I'll close it.

Please feel free to reopen it if I've misunderstood.

**Closed by danyill** 2020-02-14 01:33 UTC
Labels: bug
