### ISSUE TITLE
How to have Atom's rendering layout?

### ISSUE THREAD

**Issue by Foadsf** [asciidoctor/asciidoctor-vscode#171] opened 2019-03-15 12:06 UTC
I want to have the exact Atom's rendering layout:

![Atom layout](https://opendevise.github.io/presentation-asciidoctor-new-noteworthy-beyond/images/asciidoc-in-atom.png)

white background, code blocks in dark. I would appreciate if you could help me find the solution.

**P.S.1** Unfortunately atom gets stuck in the middle of rendering. 
**P.S.2.** vscod also does not render the syntax highlighting for some reason.
**P.S3.** [Here ](https://gist.github.com/Foadsf/44fe9b5e2bcb02b22392adf6d8f7a871)is the code I want to work on and have live preview.

**Comment by MatteoCampinoti94** [comment] 2019-03-15 12:44
I will look into the Atom's extension and see if the css they use is fully compatible and if it would look good in VSCode. Alternatively you can extract it yourself and have the previewer point at it using the `asciidoc.styles` setting.

Syntax highlighting depends on the highlighter which is not bundled with the extension, some have problems working in certain situations and some would work in the preview but not if you wanted to convert the document to PDF, for example.

Atm styling is more or less where we want it. There are problems to fix with the "editor style" preview before moving on to adding or improving things.

**Comment by Foadsf** [comment] 2019-03-16 20:30
A comparison between different options so far:

|         | Color layout | Syntax highlighting | Collapsible | Include | Other file extensions |                                       Relevant discussion                                      |
|:-------:|:------------:|:-------------------:|:-----------:|:-------:|:---------------------:|:----------------------------------------------------------------------------------------------:|
|   Atom  |       ✔️      |          ✔️          |      ❌      |    ✔️    |           ❌           | [here](https://github.com/asciidoctor/atom-asciidoc-preview/issues/200#issuecomment-473575038) |
|  VSCode |       ❌      |          ❌          |      ✔️      |    ✔️    |           ❌           |              [here](https://github.com/asciidoctor/asciidoctor-vscode/issues/171)              |
| Browser |       ~      |          ❌          |      ~✔️     |    ❌    |           ✔️           |         [here](https://github.com/asciidoctor/asciidoctor-browser-extension/issues/276)        |

**Comment by MatteoCampinoti94** [comment] 2019-04-18 12:24
@Foadsf I've looked into using the same style as Atom's preview, specifically for code listings.

Atom's preview extension uses a small extra .less file to darken the background of pre (code listing) tags. It'd be entirely possible to use it for our extension, but I believe it'd be better to leave the default style as it was intended, otherwise one might think that the preview reflects the end result and then get a different-looking HTML (or PDF, EPUB, etc...) after processing it.

The next update will allow to use your own stylesheet for the preview and the PDF conversion, so you can simply take the stylesheet from Atom's preview extension and point at it in your settings.json.

As per the syntax highlighting, I honestly have no idea why it doesn't work when using asciidoctor.js (the default setting). It does work as expected when using asciidoctor (the Ruby version), so if you need it in your preview you can set `asciidoc.use_asciidoctor_js"` to `false`. Remember also that highlightjs is very basic, so you might have to set `:source-highlighter:` to coderay, pygments or rouge depending on your language.

Also what do you mean exactly with color layout?

**Comment by MatteoCampinoti94** [comment] 2019-05-06 21:29
@Foadsf, the new releases (^2.7.0) allow to set your own css for the preview. You can now use the one from Atom's extension just by pointing to it in the settings. It needs to be a local file though, if you want to use it remotely then just point the setting to a dummy one with a remote import inside it.

**Comment by MatteoCampinoti94** [comment] 2019-05-06 21:30
Closing this issue since there have been no new comments from the other user.

**Closed by MatteoCampinoti94** 2019-05-06 21:30 UTC
Labels: enhancement
