### ISSUE TITLE
Links don't work properly

### ISSUE THREAD

**Issue by rschuetzler** [asciidoctor/asciidoctor-vscode#99] opened 2018-07-23 20:00 UTC
I might be doing something wrong, but here's an example of a link in one of my documents:

`* https://jvns.ca/networking-zine.pdf[Networking, Ack! Zine]`

In the Asciidoc output it works fine, but inside the document when editing, the link becomes (`https://jvns.ca/networking-zine.pdf[Networking`), so if I click the link to visit a site, I get an error because `[Networking` is not a part of the URL.

**Comment by FatihBozik** [comment] 2019-10-20 13:21
Hi @rschuetzler ,

It's a long time since the issue was opened. I can't reproduce it. 
Can you test if the issue continues in the last version?

**Comment by anthonyvdotbe** [comment] 2019-10-20 18:16
I can reproduce it with v2.7.6 and the following environment:

Version: 1.39.2 (user setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by FatihBozik** [comment] 2019-10-20 18:50
Ok. It's my fault. I can reproduce the issue when I try again.

**Comment by sanzoghenzo** [comment] 2020-02-03 10:31
duplicate of #116 

It's actually a vscode issue: microsoft/vscode#67022

**Comment by ieugen** [comment] 2021-01-03 20:02
The recommendation is to fix this with a link provider for asciidoc filetype https://github.com/microsoft/vscode/issues/67022#issuecomment-459149908 . 

https://code.visualstudio.com/api/references/vscode-api
https://code.visualstudio.com/api/references/vscode-api#DocumentLinkProvider 
https://code.visualstudio.com/api/references/vscode-api#DocumentSelector

**Comment by danyill** [comment] 2021-10-20 23:18
We should also register a LinkProvider for `include` and `xref` file references.

**Comment by Oobiewan** [comment] 2024-01-08 10:23
There's still a problem with detecting the end of URLs in the editor, is there a chance for further improvements?
It would be good if further common scenarios could be handled such as when a URL is followed by punctuation (recognized as not being a part of the URL itself based on the following space).
![image](https://github.com/asciidoctor/asciidoctor-vscode/assets/50614240/050b7b27-5e28-4703-a11d-c7412b0beff7)

**Comment by ggrossetie** [comment] 2024-01-08 21:51
Could you please copy/paste the text in your screenshot so we can add it in our test suite?

**Comment by Oobiewan** [comment] 2024-01-09 15:25
Hi, here's the example:
```
You can refer to a URL such as https://github.com/asciidoctor/asciidoctor-vscode/, and continue the sentence or the paragraph. The end of the URL is never recognized therefore highlighting and Ctrl+click are broken. 
```

**Closed** 2024-02-03 07:34 UTC
Labels: ✨ enhancement, 👋 help wanted
