### ISSUE TITLE
Issue with include resolution

### ISSUE THREAD

**Issue by ruku320** [asciidoctor/asciidoctor-vscode#130] opened 2018-11-19 20:25 UTC
Using v1.0.100 and the directory tree in these files: 
[test.zip](https://github.com/asciidoctor/asciidoctor-vscode/files/2596943/test.zip)

Launching the preview for the file test_inc.adoc shows an error:
![include error](https://user-images.githubusercontent.com/17328958/48732985-3acd5580-ec0f-11e8-9f41-1f92344f4cf4.png)

Don't see this issue when I revert to v1.0.2 that's on the marketplace.

**Comment by joaompinto** [comment] 2018-11-20 13:18
@ruku320 I am unable to reproduce the problem with the attached zip, could you plase test again using the VSIX available from https://github.com/asciidoctor/asciidoctor-vscode/releases/tag/v1.0.100 ?

Are you using Linux or Windows ?

Thanks

**Comment by joaompinto** [comment] 2018-11-20 21:09
I will try to test it on Windows in the next days.
The tokens.filter is an error related to a non implemented feature, it is not the cause for the include problem.

Thanks

**Comment by joaompinto** [comment] 2018-11-21 15:29
I am not able to reproduce on my Windows 10 system:
![vscode-asciidoctor](https://user-images.githubusercontent.com/1143125/48851169-4b620500-eda2-11e8-90e8-89822a039bef.PNG)

**Comment by ruku320** [comment] 2018-11-21 15:42
I updated the adoc files to display the docdir attribute:
[test.zip](https://github.com/asciidoctor/asciidoctor-vscode/files/2604799/test.zip)

Using v1.0.2:
![1 0 2 test_inc](https://user-images.githubusercontent.com/17328958/48851408-fe1d6d80-ed78-11e8-9852-96b5c5144762.png)

Using v1.0.100:
![1 0 100 test_inc](https://user-images.githubusercontent.com/17328958/48851417-0675a880-ed79-11e8-98d7-f99ade08505f.png)

Since the inclusion path should be relative it seems like v1.0.2 has the correct docdir attribute whereas v1.0.100 does not.

**Comment by joaompinto** [comment] 2018-11-21 16:10
@ruku320 Was able to reproduce with your help, fixed on 1.101:
https://github.com/asciidoctor/asciidoctor-vscode/releases/tag/v1.0.101

Please let me know if it works for you.

**Comment by ruku320** [comment] 2018-11-21 17:41
v1.0.101 fixes the include issue but seems to be missing the fix for links resolution in v1.0.100. Images are not appearing in the preview correctly with v1.0.101.

**Comment by joaompinto** [comment] 2018-11-21 18:39
@rahmanusta ,
Fixed on v1.0.102, https://github.com/asciidoctor/asciidoctor-vscode/releases/tag/v1.0.102

Thanks for the patience.

**Comment by ruku320** [comment] 2018-11-21 21:55
v1.0.102 seems to have everything working now.  Thanks for the updates.

**Comment by joaompinto** [comment] 2018-11-28 17:30
Closed with the release of v2.0.0

**Closed by joaompinto** 2018-11-28 17:30 UTC
