### ISSUE TITLE
`:: (` !with blank! breaks further highlighting

### ISSUE THREAD

**Issue by ac2epsilon** [asciidoctor/asciidoctor-vscode#219] opened 2019-08-24 16:04 UTC
\`:: (\` with blank breaks highlighting. 
- real output not affected
- without blank works fine 
- possible dup #197 (nested patterns)
- also: not explored thoroughly, but \`((\` ,  \`(*)\` also makes chaos with h-lights

Version: 1.37.1
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:17:25.463Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-20-generic

**Comment by danyill** [comment] 2020-02-13 22:27
Could you please provide an example and check whether this is a problem with the latest extension version?

We've recently changed the syntax highlighting approach and that may have eliminated this issue.

**Comment by danyill** [comment] 2020-02-22 06:03
Closing due to lack of reproducible example. Feel free to re-open this if you'd like to provide further information.

**Closed by danyill** 2020-02-22 06:03 UTC
