### ISSUE TITLE
.asciidoctorconfig.adoc seems not to work for the imagesdir

### ISSUE THREAD

**Issue by frankbenoit** [asciidoctor/asciidoctor-vscode#808] opened 2023-10-28 16:17 UTC
I would like to set the imagesdir to the relative "images" directory.
So I can use 
````
image:my.png[]
````
without the directory.

When I place the :imagesdir: in the document start, it works.
When I place it in a `.asciidoctorconfig.adoc` beside my adoc file, it does not work.

In that file, I tried:

````
:imagesdir: {asciidoctorconfigdir}/images
:imagesdir: ./images
````

AsciiDoc extension  v3.1.6

**Comment by ggrossetie** [comment] 2023-10-28 21:15
I cannot reproduce:

![image](https://github.com/asciidoctor/asciidoctor-vscode/assets/333276/c4c5a404-2a90-49fb-b349-a3e7024241d2)

Could you please provide a workspace (git repository) where you have this issue?

**Comment by frankbenoit** [comment] 2023-10-29 17:40
I tried to reproduce like you, and it worked. Then I examined my project and added debugging outputs.
Finally I found that a config file from a sibling directory is loaded.

In my project with have a log of eclipse plugin project and they are named like the main java package they contain.

Structure is like this

````
root
  features
  plugins
    com.company.a1
      .asciidoctorconfig.adoc
      documentation/...
    com.company.a2
      .asciidoctorconfig.adoc
      documentation/...
    com.company.a3
      .asciidoctorconfig.adoc
      documentation/...
    com.company.a3.b
      .asciidoctorconfig.adoc
      documentation/... <inside here I have the problem>
````

I modified all the contained .asciidoctorconfig.adoc to have a text.
Now in my `com.company.a3.b/documentation`, I find an output of `com.company.a3`


com.company.a3.b
com.company.a3.b/documentation
com.company.a3 << this is unexpected! This should be completely unrelated

Is it possible that in the plugin it takes dots in paths as directory separators?

I tried to re-create this in small, but without luck. Can you already do something with this description above?

**Comment by frankbenoit** [comment] 2023-11-04 14:32
@ggrossetie  After update to 3.1.7, i notice that it seems to works for me.

**Comment by ggrossetie** [comment] 2023-11-04 19:06
We feed two birds with one scone! 🎉 
We are not using `fsPath` anymore (but `path`) and we compute the parent directory by removing the last segment (using `/` as a separator) might be the reason why it's working as expected now.

Fixed in https://github.com/asciidoctor/asciidoctor-vscode/commit/fec9b777dfe6870659dd3baf1f3bc3cd53bbd8dc

**Closed by ggrossetie** 2023-11-04 19:06 UTC
Labels: 🐞 bug
